### PR TITLE
Document data type mappings

### PR DESCRIPTION
**Pull request by josephtaylor**
Took me a little bit to find the mappings in the integration test (was looking specifically for decimal).

### CODE REVIEW

**Comment by mmatczuk** [comment]
Hi guys, thanks for the contribution. All this actually relates to gocql the driver but I'd be happy to accept the donation. There is an inconsistency, however, with list and maps, what with `list<int>`? Another thing that would be good to add is UDT and custom marshallers. Let me know WDYT.

**Comment by mmatczuk** [comment]
My suggestion would be to eliminate collections from the table and somewhat describe it underneath.

**Comment by josephtaylor** [comment]
Yeah that makes sense cause the collection ones are more examples than definitions

**Comment by josephtaylor** [comment]
Going back to your original comment, I think you're right! Since this is really describing the functionality of the gocql driver, maybe this isn't the best place for it to be documented? :man_shrugging:

**Pull request closed without merging**
