### PR TITLE
Naive attempt at implementing CAS support

### PR DESCRIPTION
**Pull request by Linuturk**
Per #98

### CODE REVIEW

**Comment by Linuturk** [comment]
I've applied these changes to my internal project and I am testing it now. I'm not sure of the ramifications of these changes and am looking for feedback.

**Comment by dahankzter** [comment]
This looks good but lacking a bit I think. Perhaps we should also implement the other CAS operations as provided by the driver? Also if at all possible we should also have tests for these operations. I assume you are running Cassandra of some recent version? Scylla is in the process of implementing LWT so that caveat we should perhaps list somewhere in the docs as well.

**Comment by mmatczuk** [comment]
I do not think that solves it, as [Queryx embeds Query](https://github.com/scylladb/gocqlx/blob/master/queryx.go#L85) you can call `MapScanCAS` on Queryx directly. What is needed is CAS versions of BindStruct, Get etc.

**Comment by Linuturk** [comment]
I'd agree with @mmatczuk based on my testing yesterday. With my changes every CAS query comes back with `applied` equal to `false`.

**Comment by mmatczuk** [comment]
Fixed in #147

**Pull request closed without merging**
