### PR TITLE
Update GH actions

### PR DESCRIPTION
**Pull request by MrWormHole**
Aims to hotfix https://github.com/scylladb/gocqlx/issues/232 for gihub CI pipeline, will be squashed and signed on approval

### CODE REVIEW

**Comment by mmatczuk** [comment]
Please bump Golang CI version to v1.45.2 here and in the makefile.

**Comment by MrWormHole** [comment]
> Please bump Golang CI version to v1.45.2 here and in the makefile.

done, give it a go pls

**Comment by mmatczuk** [comment]
Thanks, I'm merging but the new linter needs to be configured.

**Comment by MrWormHole** [comment]
what my suggestion would be is to go for 1.38.0 rather than the latest v1.45.2

**Pull request merged**
