### PR TITLE
run travis integration tests on scylla

### PR DESCRIPTION
**Pull request by mmatczuk**

### CODE REVIEW

**Comment by penberg** [comment]
Why not run on *both* Apache Cassandra and ScyllaDB?

**Comment by mmatczuk** [comment]
Sure can do that, are the Scylla flags OK?

**Comment by penberg** [comment]
@mmatczuk Why do you need `--enable-in-memory-data-store`? Otherwise looks OK to me.

**Comment by mmatczuk** [comment]
Not to write on disk during the test

**Comment by penberg** [comment]
@mmatczuk Not write to disk to make the tests run faster? I don't object to using it, but I doubt it will show any significant difference. Up to you.

**Comment by mmatczuk** [comment]
It's not the point, it runs in a Travis docker and we try to be nice to Travis by eliminating the writes.

**Comment by mmatczuk** [comment]
@penberg please take a look

**Comment by penberg** [comment]
:+1:

**Pull request merged**
