### PR TITLE
Release v3 - change v2 suffix to v3

### PR DESCRIPTION
**Pull request by sylwiaszunejko**
Because of recent changes there is a need for a new major release. Changes are switching to scylladb/gocql and replacing Unsafe with Strict mechanism.

### CODE REVIEW

**Comment by sylwiaszunejko** [comment]
I have a problem with `cmd/schemagen`. I cannot use `v3` there (e.g. in `cmd/schemagen/testdata/go.mod`) because release is not done yet. And because I changed module name in `go.mod` I had to add `github.com/scylladb/gocqlx/v2 v2.8.0` to requirements to use `v2` in `cmd/schemagen`. I am not sure how to do it better. 
Now there will be a need for a second PR after the release to remove `github.com/scylladb/gocqlx/v2 v2.8.0` from requirements and to change `v2` to `v3` in `cmd/schemagen`

**Comment by dkropachev** [comment]
@sylwiaszunejko , I have pushed commit that solves problem with `schemagen`, please take a look.

**Comment by sylwiaszunejko** [comment]
@dkropachev I don't know why but when I tried `github.com/scylladb/gocqlx/v3 v3.0.0` in schemagen `go.mod` tests failed. Now it seems to work, maybe I did something wrong in the code

**Review by dkropachev — APPROVED** [review]
Please don't forget to tag it when it is merged, or before the merge.

**Comment by dkropachev** [comment]
> @dkropachev I don't know why but when I tried `github.com/scylladb/gocqlx/v3 v3.0.0` in schemagen `go.mod` tests failed. Now it seems to work, maybe I did something wrong in the code

It is my bad, on last PR to `schemagen` I have introduced test that actually compiles code from the test.
But I have missed the fact that it uses `gocqlx` as a external library, while it should be replaced with content from file system.

**Comment by sylwiaszunejko** [comment]
> Please don't forget to tag it when it is merged, or before the merge.

I thought the correct steps were:
1. merge this PR
2. create a tag
3. create a release from tag

**Comment by sylwiaszunejko** [comment]
> I thought the correct steps were:
>
>  1. merge this PR
>  2. create a tag
>  3. create a release from tag


@mmatczuk Could you have a look at the PR? and confirm if I am right about steps for release?

**Comment by sylwiaszunejko** [comment]
@roydahan could you look at this?

**Review by roydahan — APPROVED** [review]

**Comment by roydahan** [comment]
Looks fine to me.
We will need to highlight it in the release notes.

**Pull request merged**
