### PR TITLE
qb.BatchBuilder: Remove deprecated flag and add comments on its limit…

### PR DESCRIPTION
**Pull request by GingerMoon**
…ation and warning

### CODE REVIEW

**Comment by mmatczuk** [comment]
Please fix linting, maybe change to single line comments.

**Comment by GingerMoon** [comment]
Done.

**Comment by GingerMoon** [comment]
@mmatczuk Any more comment? Should we keep the "Deprecated" flag?

**Comment by mmatczuk** [comment]
We can drop the deprecated flag, I have no intention to remove it. In some cases it may work better.

**Comment by GingerMoon** [comment]
OK. the Deprecated flag is added back.

**Pull request merged**
