### PR TITLE
qb: add named limit and per partition limit clauses

### LINKED ISSUE #191: Add named limit to QueryBuilder
Hi guys,
I was wondering if there is a possibility of adding an option to add named limit to query builder?
Currently, we can only use the `Limit` function and it injects the limit parameter directly into the statement.

### PR DESCRIPTION
**Pull request by N1cOs**
Resolve #191

### CODE REVIEW

**Comment by mmatczuk** [comment]
Besides the new test cases what is the benefit of this change.

**Comment by N1cOs** [comment]
> Besides the new test cases what is the benefit of this change.

What do you mean? I added two new methods: `LimitNamed` and `LimitPerPartitionNamed`. It resolves issue #191 and my duplicate issue #207

**Comment by mmatczuk** [comment]
That's fine.

**Comment by mmatczuk** [comment]
Thanks.

**Comment by N1cOs** [comment]
By the way I also fixed the problem that `PER PARTITION LIMIT` clause must be before the `LIMIT` clause

**Comment by mmatczuk** [comment]
That's excellent, thanks!

**Pull request merged**
